name: flutter_template
description: Template for Flutter Riverpod applications

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  ###
  # Dependencies
  ###
  connectivity_plus: ^5.0.2
  device_info_plus: ^9.1.1
  dio: ^5.4.0
  geolocator: 9.0.2
  intl: ^0.18.1
  location: 4.4.0
  logger_fork: 1.2.0
  logger_flutter_fork: 1.2.0
  package_info_plus: ^4.2.0
  path_provider: 2.0.11
  permission_handler: ^11.1.0
  url_launcher: ^6.2.3
  go_router: ^13.0.1
  flutter_dotenv: ^5.1.0
  pretty_dio_logger: ^1.3.1

  # Freezed
  freezed_annotation: ^2.4.1
  json_serializable: ^6.7.1

  # UI
  flutter_svg: ^2.0.9
  flutter_screenutil: ^5.9.0
  flutter_staggered_animations: 1.1.1
  video_player: ^2.8.1
  google_fonts: ^6.1.0
  easy_localization: ^3.0.3
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  flutter_image_compress: ^2.1.0

  # Riverpod
  flutter_riverpod: ^2.4.9

  # Hive
  hive: 2.2.3
  hive_flutter: 1.1.0

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0

  # Auth
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  ###
  # Dev Dependencies
  ###
  build_runner: ^2.4.7
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.9
  hive_generator: ^2.0.1
  freezed: ^2.4.6

# Trigger code generation
# dart run build_runner build --delete-conflicting-outputs

# Configuration for 'flutter_launcher_icons'
# Run icon generation with 'flutter pub run flutter_launcher_icons:main'
flutter_icons:
  android: true
  ios: true
  image_path: 'assets/icon.png'
  adaptive_icon_background: '#FFFFFF'
  adaptive_icon_foreground: 'assets/icon.png'

# Configuration for 'flutter_native_splash'
# Run splash screen generation with 'flutter pub run flutter_native_splash:create'
flutter_native_splash:
  android: true
  ios: true
  color: '#FFFFFF'
  image: 'assets/icon.png'

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/translations/
    - assets/icons/
    - assets/images/
    - assets/movie_list.json
